import { ChatMessage } from "./chatManager";

export type Platform = "local" | "kaggle" | "colab";
export type OutputFormat = "py" | "ipynb";
export type Architecture = "resnet" | "transformer" | "custom_cnn" | "mlp" | "custom";

export interface ScriptGenRequest {
  architecture: Architecture;
  task: string;
  platform: Platform;
  outputFormat: OutputFormat;
  epochs: number;
  optimizer: string;
  extraNotes: string;
}

const ARCH_HINTS: Record<Architecture, string> = {
  resnet: "ResNet-50 (torchvision.models.resnet50, pretrained=True) for image classification/fine-tuning",
  transformer: "Transformer encoder model for sequence classification or regression",
  custom_cnn: "Custom CNN with Conv2d → BatchNorm → ReLU → MaxPool → Linear layers",
  mlp: "Multi-layer perceptron (fully-connected layers with BatchNorm and Dropout)",
  custom: "User-defined architecture (provide a placeholder class)",
};

const PLATFORM_HEADERS: Record<Platform, string> = {
  local: "# Local GPU training script",
  kaggle: `# Kaggle GPU training script
# Add this to a Kaggle Notebook cell or run as a script
# !pip install arc-training --quiet`,
  colab: `# Google Colab training script
# Run in a Colab cell:
# !pip install arc-training --quiet
# Then paste the rest below`,
};

/**
 * Builds the chat messages array for a script generation request.
 */
export function buildScriptGenMessages(req: ScriptGenRequest): ChatMessage[] {
  const systemPrompt = `You are ARC Script Generator, an expert PyTorch engineer who writes clean, production-ready training scripts that are pre-instrumented with arc-training hooks.

## Rules for every script you generate:
1. Import arc-training at the top: \`import arc\` or \`from arc import wrap\`
2. Wrap the model: \`model = arc.wrap(model)\` immediately after model instantiation
3. Include a try/except block around the training loop to catch and log exceptions
4. Include checkpoint logic: save model state_dict every N epochs using \`torch.save\`
5. The backward() pass must NOT be replaced — arc patches it automatically via \`arc.wrap()\`
6. Add a \`# Generated by ARC Lens Pro — ARC-tested ✓\` comment at the very top
7. Keep the script clean, well-commented, and production-ready

## Output format
- If outputFormat is "py": output a single complete Python script inside a \`\`\`python block
- If outputFormat is "ipynb": output a series of cells as JSON in \`\`\`json format following the Jupyter notebook v4 schema

Do NOT include any prose outside the code block. Just the code.`;

  const userPrompt = `Generate a complete PyTorch training script with the following specifications:

- **Architecture**: ${ARCH_HINTS[req.architecture]}
- **Task**: ${req.task}
- **Platform**: ${req.platform} — prepend: ${PLATFORM_HEADERS[req.platform]}
- **Output format**: ${req.outputFormat === "py" ? "Python .py script" : "Jupyter .ipynb notebook"}
- **Epochs**: ${req.epochs}
- **Optimizer**: ${req.optimizer} (with appropriate LR scheduler)
- **Extra requirements**: ${req.extraNotes || "None"}

Remember: the script must use \`arc.wrap(model)\` and include proper checkpointing.`;

  return [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];
}

/**
 * Extracts the code block from the LLM response.
 */
export function extractCodeBlock(response: string, format: OutputFormat): string | null {
  const lang = format === "py" ? "python" : "json";
  const regex = new RegExp("```" + lang + "\\s*([\\s\\S]*?)```", "i");
  const match = response.match(regex);
  if (match) return match[1].trim();
  // Fallback: return raw if no code fence found
  const anyFence = response.match(/```[\s\S]*?\n([\s\S]*?)```/);
  return anyFence ? anyFence[1].trim() : null;
}
